# Encoding classical data on quantum computers

#### This tutorial demonstrates various data encoding techniques using pieces of code from Penny-Lane and Qiskit - two open source libraries for quantum computing. For more info, check out:https://qiskit.org/documentation/ and https://pennylane.readthedocs.io/en/stable/

# Basis encoding - PennyLane

# PennyLane templates

In [1]:
import pennylane as qml
from pennylane import numpy as np

# import the template
from pennylane.templates.embeddings import BasisEmbedding

In [35]:
# create some binary data
data = np.array([1,0,1])
# crate quantim device - pennylane default qubit simulator
dev = qml.device('default.qubit', wires=3)
# create a q-node, dealing with a quantum circuit
@qml.qnode(dev)
# basis encoding
def circuit(data):
    BasisEmbedding(features=data, wires=range(3))
    return qml.expval(qml.PauliZ(0)), qml.expval(qml.PauliZ(1)), qml.expval(qml.PauliZ(2))

In [36]:
circuit(data)

ValueError: 'basis_state' must only consist of 0s and 1s; got [<Variable(data[0]:0)> <Variable(data[1]:1)> <Variable(data[2]:2)>]

# Angle encoding - PennyLane


#### Import some data

In [4]:
from sklearn.datasets import load_iris
from sklearn.utils import shuffle
from sklearn.preprocessing import normalize
np.random.seed(42)

In [5]:
# loading data
x, y = load_iris().data, load_iris().target
x, y = shuffle(x, y)

# take the first 5
x = x[:5]
y = y[:5]

In [6]:
print(x, y)

[[6.1 2.8 4.7 1.2]
 [5.7 3.8 1.7 0.3]
 [7.7 2.6 6.9 2.3]
 [6.  2.9 4.5 1.5]
 [6.8 2.8 4.8 1.4]] [1 0 2 1 1]


In [7]:
# normalize the data
data = normalize(x)
print(data)

[[0.73659895 0.33811099 0.56754345 0.14490471]
 [0.8068282  0.53788547 0.24063297 0.04246464]
 [0.70600618 0.2383917  0.63265489 0.21088496]
 [0.73350949 0.35452959 0.55013212 0.18337737]
 [0.76467269 0.31486523 0.53976896 0.15743261]]


# Angle Encoding

In [8]:
# Import the PennyLane template for angle embedding
from pennylane.templates.embeddings import AngleEmbedding

In [12]:
# no of qubits is the number of your data features
num_qubits = 4

dev = qml.device('default.qubit', wires=num_qubits)

@qml.qnode(dev)
def circuit(data):
    # apply Hadamards to all qubits in the circuit
    for i in range(num_qubits):
        qml.Hadamard(wires=i)
    AngleEmbedding(features=data, wires=range(num_qubits), rotation='Y')
    return qml.expval(qml.PauliZ(0)), qml.expval(qml.PauliZ(1)), qml.expval(qml.PauliZ(2)), qml.expval(qml.PauliZ(3))

In [14]:
circuit(data[3])

array([-0.6694807 , -0.34714924, -0.52279986, -0.18235135])

In [25]:
# encode all data

@qml.qnode(dev)
def circuit(data):
    # apply Hadamards to all qubits in the circuit
    for i in range(num_qubits):
        qml.Hadamard(wires=i)
    
    for i in range(len(data)):
        AngleEmbedding(features=data[i], wires=range(num_qubits), rotation='Y')
    return qml.expval(qml.PauliZ(0)), qml.expval(qml.PauliZ(1)), qml.expval(qml.PauliZ(2)), qml.expval(qml.PauliZ(3))

In [26]:
circuit(data)

array([ 0.56960308, -0.97740396, -0.57357236, -0.67359663])

# Angle Encoding -  Qiskit

In [39]:
from qiskit import *
from qiskit.circuit.    

ModuleNotFoundError: No module named 'qiskit.circuit.library'

In [ ]:
qiskit.circuit.